[package]
name = "stp-cli"
version = "0.1.0"
authors = ["Nathan Miller <nathanm2@gmail.com>"]
edition = "2018"

[[bin]]
name = "stp"
path = "src/main.rs"

[dependencies]
stp-core = { path = "../stp-core" }
clap = "~2.33.1"
